# import Tag from 'Tag.gql'
# import Schedule from 'Schedule.gql'
type Tour {
  id: Int!,
  name: String!,
  schedules: [Schedule]!,
  description: String!,
  max_people: Int!,
  cost: Float!,
  all_included: Boolean!,
  min_age: Int!,
  ranking: Int!,
  tags: [Tag]!
}

type Query {
  tours: [Tour]!
  tour(id: Int!): Tour!
}